services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=coursereview
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d coursereview"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  cache:
    image: valkey/valkey:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    image: coursereview
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://cache:6379/0
      - DEBUG=False
    restart: unless-stopped

volumes:
  postgres_data:
