[project]
name = "course-review"
requires-python = ">=3.14, <3.15"
version = "0.0.1"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "bpython>=0.26",
    "dj-database-url>=3.1.2",
    "django>=6.0.2",
    "django-cors-headers>=4.9.0",
    "django-debug-toolbar>=6.2.0",
    "django-redis>=6.0.0",
    "djangorestframework>=3.16.1",
    "gunicorn>=25.1.0",
    "httpx>=0.28.1",
    "psycopg[binary]>=3.3.3",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.2.1",
    "pytz>=2025.2",
    "pyyaml>=6.0.3",
    "redis>=7.2.1",
    "requests>=2.32.5",
]

[tool.uv]
package = false

[dependency-groups]
dev = [
    "prek>=0.3.3",
]
lint = [
    "ruff>=0.15.2",
]
