# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spider", "0002_alter_crawleddata_current_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawleddata",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("medians", "Medians"),
                    ("orc_department_courses", "ORC Department Courses"),
                    ("course_timetable", "Course Timetable"),
                    ("course_offerings", "Course Offerings"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
