# Generated by Django 5.0.8 on 2024-09-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_student_unauth_session_ids'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='course_topics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='pre_requisites',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('course_code',), name='unique_course_code'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='source',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subnumber',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
    ]
