# Generated by Django 5.0.8 on 2024-09-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(db_index=True, default='', max_length=10, unique=True),
        ),
    ]
