# Generated by Django 5.2 on 2025-07-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_course_number_alter_course_course_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="difficulty_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="course",
            name="quality_score",
            field=models.FloatField(default=0.0),
        ),
    ]
