# Generated by Django 5.2 on 2025-10-02 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_reviewvote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="confirmation_link",
        ),
        migrations.RemoveField(
            model_name="student",
            name="unauth_session_ids",
        ),
    ]
