# Generated by Django 5.2 on 2025-10-13 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_remove_student_confirmation_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="dislike_count",
        ),
        migrations.RemoveField(
            model_name="review",
            name="kudos_count",
        ),
    ]
