# Generated by Django 5.2.8 on 2025-12-03 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0010_remove_review_dislike_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="difficulty_score",
        ),
        migrations.RemoveField(
            model_name="course",
            name="quality_score",
        ),
    ]
