# Generated by Django 5.2.8 on 2026-01-03 23:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0011_remove_course_difficulty_score_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseoffering",
            name="term",
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="review",
            name="term",
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["course", "category", "value"],
                name="web_vote_course__b117a9_idx",
            ),
        ),
    ]
