# Generated by Claude 2026-09-05: add "rejected" status to Syllabus

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0014_syllabusfile_syllabus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syllabus",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("analyzed", "Analyzed"),
                    ("rejected", "Rejected"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
    ]
